server:
  port: 8081
spring:
  application:
    name: GoBooking
  datasource:
    url: jdbc:mysql://localhost:3306/go_booking?createDatabaseIfNotExist=true
    username: root
    password: root
  liquibase:
    change-log: classpath:/db/changelog.xml
  mail:
    host: smtp.gmail.com
    username: mailsenderforjava@gmail.com
    password: iltifceckjkwsohf
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          ssl:
            trust: smtp.gmail.com
site:
  url: http://localhost:8081
image:
  upload:
    path: C:/Users/hovha/IdeaProjects/GoBooking/img
jwt:
  secret: R29Cb29raW5nIGlzIHZlcnkgZ29vZCBuaWNlIGJlYXR5ZnVsIGFwcGxpY2F0aW9uIGluIHRoZSB3b3JsZCBhbmQgZ2FsYWN0aWM=
  expiration: 600000